# Accept traffic on the port provided by Render
http_port MY_RENDER_PORT

# Basic access control (Allows everyone)
acl allsrc src all
http_access allow allsrc

# Correctly route logs to container outputs
logfile_rotate 0
access_log stdio:/dev/stdout
cache_log stderr

# Prevent squid from trying to look for a physical disk cache directory
cache dir null /tmp
